# Generated by Django 5.1.1 on 2024-09-18 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NonFunctionalRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StartupDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=255, unique=True)),
                ('idea_description', models.TextField()),
                ('business_domain', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authentication', models.TextField()),
                ('authorization', models.TextField()),
                ('non_functional_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nonfunctionalrequirements')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.startupdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Scalability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_number_of_users', models.IntegerField()),
                ('expected_number_of_transactions_per_second', models.IntegerField()),
                ('non_functional_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nonfunctionalrequirements')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.startupdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Reliability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uptime', models.CharField(max_length=255)),
                ('backup', models.CharField(max_length=255)),
                ('recovery', models.CharField(max_length=255)),
                ('non_functional_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nonfunctionalrequirements')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.startupdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time', models.CharField(max_length=255)),
                ('throughput', models.CharField(max_length=255)),
                ('non_functional_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nonfunctionalrequirements')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.startupdetails')),
            ],
        ),
        migrations.AddField(
            model_name='nonfunctionalrequirements',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.startupdetails'),
        ),
        migrations.CreateModel(
            name='Maintainability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_quality', models.TextField()),
                ('documentation', models.TextField()),
                ('monitoring', models.TextField()),
                ('non_functional_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nonfunctionalrequirements')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.startupdetails')),
            ],
        ),
        migrations.CreateModel(
            name='FunctionalRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_domain', models.CharField(max_length=255)),
                ('application_features', models.JSONField()),
                ('data_management', models.JSONField()),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.startupdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_provider', models.CharField(max_length=255)),
                ('deployment_model', models.CharField(max_length=255)),
                ('non_functional_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nonfunctionalrequirements')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.startupdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.CharField(max_length=255)),
                ('cost_estimation', models.TextField()),
                ('licensing', models.TextField()),
                ('non_functional_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nonfunctionalrequirements')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.startupdetails')),
            ],
        ),
    ]
